version: '3.8'
services:
  webservice:
    build: .
    ports:
      - "5005:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://user:password@db/mydatabase
    image: flaskapp
    
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
